<?php include "Dockerfile"; ?>

ENV BIN_DIR "/usr/local/bin"
RUN apt-get update \
    && apt-get install -y cron git groff mysql-client python-pip rsyslog sudo \
    && pip install awscli \
    && curl --retry 10 --retry-delay 3 https://getcomposer.org/installer | php -- --install-dir=$BIN_DIR --filename=composer \
    && curl --retry 10 --retry-delay 3 -L https://github.com/punkstar/mageconfigsync/releases/download/0.4.0/mageconfigsync-0.4.0.phar -o $BIN_DIR/mageconfigsync && chmod +x $BIN_DIR/mageconfigsync \
    && curl --retry 10 --retry-delay 3 https://s3-eu-west-1.amazonaws.com/magedbm-releases/magedbm.phar -o $BIN_DIR/magedbm.phar && chmod +x $BIN_DIR/magedbm.phar \
    && curl --retry 10 --retry-delay 3 https://files.magerun.net/n98-magerun.phar -o $BIN_DIR/n98-magerun.phar && chmod +x $BIN_DIR/n98-magerun.phar \
    && curl --retry 10 --retry-delay 3 https://raw.githubusercontent.com/colinmollenhour/modman/master/modman -o $BIN_DIR/modman && chmod +x $BIN_DIR/modman \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY bin/* $BIN_DIR/
ADD run-cron.sh /run-cron.sh

CMD ["php", "-a"]
